### ISSUE TITLE
6.1_6.2 sqlite missing table

### ISSUE THREAD

**Issue by delijati** [haiwen/seafile-server#102]
```
$ upgrade/upgrade_6.1_6.2.sh 

-------------------------------------------------------------
This script would upgrade your seafile server from 6.1 to 6.2
Press [ENTER] to contiune
-------------------------------------------------------------



Updating seafile/seahub database ...

[INFO] You are using SQLite3
[INFO] updating seahub database...
Traceback (most recent call last):
  File "/opt/haiwen/seafile-server-6.2.3/upgrade/db_update_helper.py", line 363, in <module>
    main()
  File "/opt/haiwen/seafile-server-6.2.3/upgrade/db_update_helper.py", line 358, in main
    db_updater.update_db()
  File "/opt/haiwen/seafile-server-6.2.3/upgrade/db_update_helper.py", line 259, in update_db
    super(SQLiteDBUpdater, self).update_db()
  File "/opt/haiwen/seafile-server-6.2.3/upgrade/db_update_helper.py", line 120, in update_db
    self.update_seahub_sql(seahub_sql)
  File "/opt/haiwen/seafile-server-6.2.3/upgrade/db_update_helper.py", line 283, in update_seahub_sql
    self.apply_sqls(self.seahub_db, sql_path)
  File "/opt/haiwen/seafile-server-6.2.3/upgrade/db_update_helper.py", line 273, in apply_sqls
    conn.execute(line)
sqlite3.OperationalError: no such table: sysadmin_extra_userloginlog

Failed to upgrade your database
```

**Comment by delijati** [comment]
https://forum.seafile.com/t/webinterface-broken-after-upgrading-from-6-1-to-6-2/4405/5 worked for me
