### ISSUE TITLE
Updating to Seafile Server 7.1.0 Beta caused multiple DB errors of SQLite

### ISSUE THREAD

**Issue by hehongbo** [haiwen/seafile-server#297]
Hi team, I'm trying upgrade to 7.1.0 (to get rid of Python 2) and it failed. 

It gives the following error: 

```
Updating seafile/seahub database ...

[INFO] You are using SQLite3
[INFO] updating seahub database...
Traceback (most recent call last):
  File "/data/seafile/seafile-server-7.1.0/upgrade/db_update_helper.py", line 384, in <module>
    main()
  File "/data/seafile/seafile-server-7.1.0/upgrade/db_update_helper.py", line 379, in main
    db_updater.update_db()
  File "/data/seafile/seafile-server-7.1.0/upgrade/db_update_helper.py", line 275, in update_db
    super(SQLiteDBUpdater, self).update_db()
  File "/data/seafile/seafile-server-7.1.0/upgrade/db_update_helper.py", line 129, in update_db
    self.update_seahub_sql(seahub_sql)
  File "/data/seafile/seafile-server-7.1.0/upgrade/db_update_helper.py", line 299, in update_seahub_sql
    self.apply_sqls(self.seahub_db, sql_path)
  File "/data/seafile/seafile-server-7.1.0/upgrade/db_update_helper.py", line 289, in apply_sqls
    conn.execute(line)
sqlite3.OperationalError: near "ON": syntax error

Failed to upgrade your database
```

So I dragged `seahub.db` to my local machine I realized `constance_config` becomes empty while it's contents like `SERVICE_URL` have gone to `constance_config_old`. 

After I have a look at this table's field names and change this line

https://github.com/haiwen/seafile-server/blob/e895a713c77f14240245d0ce3e0186af0487a584/scripts/upgrade/sql/7.1.0/sqlite3/seahub.sql#L6

to

```
INSERT INTO "constance_config" ("id", "constance_key", "value") SELECT "id", "key", "value" FROM "constance_config_old";
```

I got same error as above. 

It seems to have 3 errors in this query, one is the rename of `constance_key`, the other 2 are 

https://github.com/haiwen/seafile-server/blob/e895a713c77f14240245d0ce3e0186af0487a584/scripts/upgrade/sql/7.1.0/sqlite3/seahub.sql#L11

and 

https://github.com/haiwen/seafile-server/blob/e895a713c77f14240245d0ce3e0186af0487a584/scripts/upgrade/sql/7.1.0/sqlite3/seahub.sql#L12

Given the fact that [SQLite doesn't support the ADD CONSTRAINT variant of the ALTER TABLE command](https://stackoverflow.com/questions/1884818/how-do-i-add-a-foreign-key-to-an-existing-sqlite-table) and creating this constrains needs a recreation of this table, I afraid I'm not experienced enough to create a pull request. Thus I just start this issue and looking for help.

**Comment by hehongbo** [comment]
Verified fixed in https://github.com/haiwen/seafile-server/commit/f5f0b47ab967ff97ccb62b9b47e6ee00cd517934 , Good job!
