### ISSUE TITLE
Problems with upgrading from 7.0.4 to 7.1.3

### ISSUE THREAD

**Issue by chrisdecker1201** [haiwen/seafile-server#331]
Hallo,

I'm running Seafile 7.0.4 on a Ubuntu Server 16.04 and want to upgrade to 7.1.3.

I followed this instructions https://download.seafile.com/published/seafile-manual/upgrade/upgrade_notes_for_7.1.x.md and run the ./upgrade_7.0_7.1.sh but get the following error.

~~~
Updating seafile/seahub database ...

Traceback (most recent call last):
  File "/home/seafile/seafile-server-7.1.3/upgrade/db_update_helper.py", line 384, in <module>
    main()
  File "/home/seafile/seafile-server-7.1.3/upgrade/db_update_helper.py", line 378, in main
    db_updater = DBUpdater.get_instance(version)
  File "/home/seafile/seafile-server-7.1.3/upgrade/db_update_helper.py", line 84, in get_instance
    ccnet_db_info = DBUpdater.get_ccnet_mysql_info(version)
  File "/home/seafile/seafile-server-7.1.3/upgrade/db_update_helper.py", line 162, in get_ccnet_mysql_info
    password = config.get(db_section, 'PASSWD')
  File "/usr/lib/python3.6/configparser.py", line 800, in get
    d)
  File "/usr/lib/python3.6/configparser.py", line 394, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib/python3.6/configparser.py", line 444, in _interpolate_some
    "found: %r" % (rest,))
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: "%XXX"

Failed to upgrade your database
~~~

I found out that configparser needs to mask % with %% and edited seafile.conf and ccnet.conf. After that the upgrade runs successfully through with a tiny warning, which leads to a not running system. Thanks god I had a backup.

~~~
[INFO] You are using MySQL
[INFO] updating seahub database...
[WARNING] Failed to execute sql: (1091, "Can't DROP 'drafts_draft_origin_file_uuid_7c003c98_uniq'; check that column/key exists")
~~~

**Comment by chrisdecker1201** [comment]
I've now the following problem
~~~
[03/27/2020 07:44:33 AM] repo-mgr.c(894): Commit 8e27709e-c87f-496d-9ab3-4b86e1ef342d:ca67db95fdd05d95a7501fd6b0b5154f74383c13 is missing
[03/27/2020 07:44:33 AM] repo-mgr.c(894): Commit aef68cc9-0075-4e14-bd40-ed87e1bcda16:267533fe5cdb1eccaa2f4a46ad7100a20283d1bd is missing
[03/27/2020 07:44:35 AM] repo-mgr.c(894): Commit 5eba11e7-23ad-4103-a796-bd452f35f93a:3716732d6553547280c049f3145cdc3abedd1bc6 is missing
[03/27/2020 07:44:36 AM] repo-mgr.c(894): Commit 6d6651fc-d1e6-408c-aea4-25cb1b9cbd26:ea2fb3beb39860b82ee5b8c562b36d9e1d0f1a62 is missing
[03/27/2020 07:44:36 AM] repo-mgr.c(894): Commit 27700bd2-182b-41ff-b600-2330dccf57c2:0e0679b623e606a6e53abd836cadcd088ddb508b is missing
[03/27/2020 07:44:36 AM] repo-mgr.c(894): Commit 8e27709e-c87f-496d-9ab3-4b86e1ef342d:ca67db95fdd05d95a7501fd6b0b5154f74383c13 is missing
[03/27/2020 07:44:36 AM] repo-mgr.c(894): Commit aef68cc9-0075-4e14-bd40-ed87e1bcda16:267533fe5cdb1eccaa2f4a46ad7100a20283d1bd is missing
[03/27/2020 07:44:42 AM] repo-mgr.c(894): Commit 2f5eeb1d-a789-4940-b9cd-704f6a56b0b2:ea30da2d8ba906d866f3ba8fc954be013fac4aaf is missing
[03/27/2020 07:44:42 AM] repo-mgr.c(894): Commit 50986c5b-005c-4f06-a9ee-427ad2dec661:144a6b07287cbe4ff2bcd795720e4b5c4e79eabd is missing
[03/27/2020 07:45:13 AM] repo-mgr.c(894): Commit 2f5eeb1d-a789-4940-b9cd-704f6a56b0b2:ea30da2d8ba906d866f3ba8fc954be013fac4aaf is missing
[03/27/2020 07:45:13 AM] repo-mgr.c(894): Commit 50986c5b-005c-4f06-a9ee-427ad2dec661:144a6b07287cbe4ff2bcd795720e4b5c4e79eabd is missing
[03/27/2020 07:45:44 AM] repo-mgr.c(894): Commit 2f5eeb1d-a789-4940-b9cd-704f6a56b0b2:ea30da2d8ba906d866f3ba8fc954be013fac4aaf is missing
[03/27/2020 07:45:44 AM] repo-mgr.c(894): Commit 50986c5b-005c-4f06-a9ee-427ad2dec661:144a6b07287cbe4ff2bcd795720e4b5c4e79eabd is missing
[03/27/2020 07:46:01 AM] repo-mgr.c(894): Commit 414c63be-4f31-440e-b073-0055ea2fd168:d1b8db21efef4c8580d39992fe07113e01a702a8 is missing
[03/27/2020 07:46:15 AM] repo-mgr.c(894): Commit 2f5eeb1d-a789-4940-b9cd-704f6a56b0b2:ea30da2d8ba906d866f3ba8fc954be013fac4aaf is missing
[03/27/2020 07:46:15 AM] repo-mgr.c(894): Commit 50986c5b-005c-4f06-a9ee-427ad2dec661:144a6b07287cbe4ff2bcd795720e4b5c4e79eabd is missing
[03/27/2020 07:46:46 AM] repo-mgr.c(894): Commit 2f5eeb1d-a789-4940-b9cd-704f6a56b0b2:ea30da2d8ba906d866f3ba8fc954be013fac4aaf is missing
[03/27/2020 07:46:46 AM] repo-mgr.c(894): Commit 50986c5b-005c-4f06-a9ee-427ad2dec661:144a6b07287cbe4ff2bcd795720e4b5c4e79eabd is missing
[03/27/2020 07:47:17 AM] repo-mgr.c(894): Commit 2f5eeb1d-a789-4940-b9cd-704f6a56b0b2:ea30da2d8ba906d866f3ba8fc954be013fac4aaf is missing
[03/27/2020 07:47:17 AM] repo-mgr.c(894): Commit 50986c5b-005c-4f06-a9ee-427ad2dec661:144a6b07287cbe4ff2bcd795720e4b5c4e79eabd is missing
[03/27/2020 07:47:48 AM] repo-mgr.c(894): Commit 2f5eeb1d-a789-4940-b9cd-704f6a56b0b2:ea30da2d8ba906d866f3ba8fc954be013fac4aaf is missing
[03/27/2020 07:47:48 AM] repo-mgr.c(894): Commit 50986c5b-005c-4f06-a9ee-427ad2dec661:144a6b07287cbe4ff2bcd795720e4b5c4e79eabd is missing
[03/27/2020 07:48:19 AM] repo-mgr.c(894): Commit 2f5eeb1d-a789-4940-b9cd-704f6a56b0b2:ea30da2d8ba906d866f3ba8fc954be013fac4aaf is missing
[03/27/2020 07:48:19 AM] repo-mgr.c(894): Commit 50986c5b-005c-4f06-a9ee-427ad2dec661:144a6b07287cbe4ff2bcd795720e4b5c4e79eabd is missing
[03/27/2020 07:48:50 AM] repo-mgr.c(894): Commit 2f5eeb1d-a789-4940-b9cd-704f6a56b0b2:ea30da2d8ba906d866f3ba8fc954be013fac4aaf is missing
[03/27/2020 07:48:50 AM] repo-mgr.c(894): Commit 50986c5b-005c-4f06-a9ee-427ad2dec661:144a6b07287cbe4ff2bcd795720e4b5c4e79eabd is missing
~~~

**Comment by chrisdecker1201** [comment]
I updated my pull request. Probably the changes in python/seaserv/service.py are necessary too. But for now I stay at 7.0.4
