### ISSUE TITLE
seafile-admin fails to start Seahub

### ISSUE THREAD

**Issue by lkuza2** [haiwen/seafile-server#98]
After upgrading from 6.1.2 to 6.2.2, seafile-admin fails to start Seahub in WSGI mode,

```
[seafile@xxxxxx cloud.xxxxxxx]$ seafile-admin start

Starting seafile-server...
Starting seahub...
Traceback (most recent call last):
  File "/usr/bin/seafile-admin", line 972, in <module>
    main()
  File "/usr/bin/seafile-admin", line 968, in main
    args.func(args)
  File "/usr/bin/seafile-admin", line 898, in start_seafile
    start_seahub_gunicorn()
  File "/usr/bin/seafile-admin", line 696, in start_seahub_gunicorn
    if run_argv(argv, cwd=conf[CONF_SEAHUB_DIR], env=env) != 0:
  File "/usr/bin/seafile-admin", line 170, in run_argv
    env=env)
  File "/usr/lib64/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
[seafile@xxxxxxxxx cloud.xxxxxxx]$
```

**Comment by lkuza2** [comment]
I am not sure what changed but in 6.2.4 the script runs properly again.  6.2.3 it did not make sure.  Tagging you so you are aware and it doesn't regress in future version @haiwen

**Comment by TCB13** [comment]
I'm trying to install version `6.2.5` raspberry edition and I'm getting this error.

**Comment by DevelAngel** [comment]
In my humble opinion, seafile-admin must fail because seahub is not part of the seafile-server package.

seshub depends on seafile-server but not vice versa, elsewise we have a cycling dependency.

**Comment by lkuza2** [comment]
This has been fixed for me in the newest versions.
